# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    secrets:
      # Required if you plan to publish (uncomment the below)
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      # Grunt fails due to CSS styling, when needing an !important statement.
      disable_grunt: false
      disable_phpunit: true
      disable_release : true
      release_branches: main
      min_php : 7.4